# Generated by Django 4.0.1 on 2022-02-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='kekeke'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.CharField(default='sadjhs', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
