# Generated by Django 4.0.1 on 2022-02-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_description_item_image_url_item_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/'),
        ),
    ]
