# Generated by Django 4.0.1 on 2022-02-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_image_url_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='image_url',
        ),
    ]
